<a href="https://colab.research.google.com/github/TarasStasko/Python08/blob/main/Practice8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [2]:
import numpy as np

grades_list = [85, 92, 78, 90, 95]

grades_array = np.array(grades_list)

print("Student's grades as a numpy array:")
print(grades_array)


Student's grades as a numpy array:
[85 92 78 90 95]


In [3]:
import numpy as np

prices_list = [
    [2.50, 2.00, 1.50, 3.20],
    [2.70, 1.90, 1.60, 3.50],
    [2.40, 2.10, 1.70, 3.00]
]

prices_matrix = np.array(prices_list)

print("Prices matrix:")
print(prices_matrix)


Prices matrix:
[[2.5 2.  1.5 3.2]
 [2.7 1.9 1.6 3.5]
 [2.4 2.1 1.7 3. ]]


In [4]:
import numpy as np

grades_list = [85, 92, 78, 90, 95]
grades_array = np.array(grades_list)

prices_list = [
    [2.50, 2.00, 1.50, 3.20],
    [2.70, 1.90, 1.60, 3.50],
    [2.40, 2.10, 1.70, 3.00]
]
prices_matrix = np.array(prices_list)

grades_dtype = grades_array.dtype
prices_dtype = prices_matrix.dtype

print("Data type of grades values:", grades_dtype)
print("Data type of prices values:", prices_dtype)


Data type of grades values: int64
Data type of prices values: float64


In [5]:
import numpy as np

grades_list = [85, 92, 78, 90, 95]
grades_array = np.array(grades_list)

prices_list = [
    [2.50, 2.00, 1.50, 3.20],
    [2.70, 1.90, 1.60, 3.50],
    [2.40, 2.10, 1.70, 3.00]
]
prices_matrix = np.array(prices_list)

grades_shape = grades_array.shape
prices_shape = prices_matrix.shape

print("Shape of grades array:", grades_shape)
print("Shape of prices matrix:", prices_shape)


Shape of grades array: (5,)
Shape of prices matrix: (3, 4)



Масив, створений у завданні 2, має форму одновимірного масиву, оскільки він створений зі списку одновимірних даних. Оскільки масив має тільки один рівень вкладеності, його форма буде (n,), де n - кількість елементів у масиві.

In [7]:
import numpy as np

grades_list = [85, 92, 78, 90, 95]
grades_array = np.array(grades_list)

grades_column_vector = grades_array.reshape(-1, 1)

print(grades_column_vector)


[[85]
 [92]
 [78]
 [90]
 [95]]


Масиви NumPy надають багато операцій, які легко застосовувати до всього масиву за один раз.
Масиви NumPy оптимізовані для швидкості та ефективності обробки даних.
Масиви NumPy мають багато вбудованих функцій та методів для обробки даних, таких як сортування, фільтрація, статистичні обчислення і т.д., що спрощує роботу з ними.
Масиви NumPy використовують менше пам'яті.

In [8]:
import numpy as np

profit_array = np.linspace(0, 1000.50, 7)

print(profit_array)


[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


In [9]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

vertical_stack = np.vstack((array1, array2))
horizontal_stack = np.hstack((array1, array2))

print("Vertical stacking of arrays:")
print(vertical_stack)
print("\nHorizontal stacking of arrays:")
print(horizontal_stack)


Vertical stacking of arrays:
[[1 2 3]
 [4 5 6]]

Horizontal stacking of arrays:
[1 2 3 4 5 6]


In [23]:
import numpy as np


def transpose_array(arr):
    """
    Transpose the input array using reshape method.

    Parameters:
    arr (numpy.ndarray): Input array to be transposed.

    Returns:
    numpy.ndarray: Transposed array.
    """
    transposed_arr = arr.reshape(arr.shape[::-1])
    return transposed_arr


input_array = np.array([[1, 2, 3],
                        [4, 5, 6]])
transposed_array = transpose_array(input_array)
print("Original array:")
print(input_array)
print("Transposed array:")
print(transposed_array)


Original array:
[[1 2 3]
 [4 5 6]]
Transposed array:
[[1 2]
 [3 4]
 [5 6]]


In [24]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

elementwise_addition = array1 + array2

elementwise_subtraction = array1 - array2

scalar_multiplication = 2 * array1

elementwise_multiplication = array1 * array2

matrix_multiplication = np.dot(array1, array2.T)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise addition:")
print(elementwise_addition)

print("\nElement-wise subtraction:")
print(elementwise_subtraction)

print("\nScalar multiplication:")
print(scalar_multiplication)

print("\nElement-wise multiplication:")
print(elementwise_multiplication)

print("\nMatrix multiplication:")
print(matrix_multiplication)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Scalar multiplication:
[[ 2  4  6]
 [ 8 10 12]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Matrix multiplication:
[[ 50  68]
 [122 167]]


In [25]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

minimum_number = np.min(matrix)
maximum_number = np.max(matrix)
sum_of_numbers = np.sum(matrix)
min_per_row = np.min(matrix, axis=1)
max_per_column = np.max(matrix, axis=0)

print("Matrix:")
print(matrix)

print("\nMinimum number:", minimum_number)
print("Maximum number:", maximum_number)
print("Sum of numbers:", sum_of_numbers)
print("Minimum numbers for each row:", min_per_row)
print("Maximum numbers for each column:", max_per_column)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Minimum number: 1
Maximum number: 9
Sum of numbers: 45
Minimum numbers for each row: [1 4 7]
Maximum numbers for each column: [7 8 9]


In [26]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

values = matrix[1:-1, 0:2]

print("Values of the first and second column for all rows except the first and last:")
print(values)


Values of the first and second column for all rows except the first and last:
[[4 5]]


In [27]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3],
                   [7, 8, 9]])

flattened_matrix = matrix.flatten()

unique_values, frequencies = np.unique(flattened_matrix, return_counts=True)

print("Unique values in the matrix:", unique_values)
print("Frequencies of unique values:", frequencies)


Unique values in the matrix: [1 2 3 4 5 6 7 8 9]
Frequencies of unique values: [2 2 2 1 1 1 1 1 1]


In [ ]:
import numpy as np

height = 480
width = 720

image = np.zeros((height, width, 3), dtype=np.uint8)

middle_pixel_height = height // 2

image[:middle_pixel_height, :, :] = [0, 87, 184]

image[middle_pixel_height:, :, :] = [255, 215, 0]

image
